version: 0.2

env:
  secrets-manager:
    LOGIN: dev/sonar:sonartoken
    HOST: dev/sonar:HOST
    Organization: dev/sonar:Organization
    Project: dev/sonar:Project


# phases:
#   install:
#     runtime-versions:
#       nodejs: 20
#     commands:
#       - echo "==== install phase ===="
#       - echo "Installing node deps"
#       - npm ci
#       - echo "Installing sonar-scanner CLI"
#       - npm install -g sonar-scanner
#       - echo "AWS CLI version:"
#       - aws --version
#       - echo "Logging into ECR"
#       - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 123456789012.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com) || true
#   pre_build:
#     commands:
#       - echo "==== pre_build phase ===="
#       - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
#       - echo "IMAGE_TAG=$IMAGE_TAG"
#   build:
#     commands:
#       - echo "==== build phase ===="
#       - echo "Running unit tests"
#       - npm test
#       - echo "Running SonarQube analysis"
#       # sonar-scanner will pick up SONAR_TOKEN from env; we use -D to provide the key/url/project
#       - |
#         set -o pipefail
#         sonar-scanner \
#           -Dsonar.projectKey=$SONAR_PROJECT_KEY \
#           -Dsonar.sources=. \
#           -Dsonar.host.url=$SONAR_HOST_URL \
#           -Dsonar.login=$SONAR_TOKEN 2>&1 | tee sonar-output.txt
#       - echo "Sonar scanner exit code: ${PIPESTATUS[0]}"
#       - echo "Building Docker image"
#       - docker build -t $APP_NAME:$IMAGE_TAG .
#       - docker tag $APP_NAME:$IMAGE_TAG 123456789012.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo "==== post_build phase ===="
#       - echo "Pushing image to ECR"
#       - docker push 123456789012.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:$IMAGE_TAG
#       - echo "Deploying to staging for DAST"
#       - jq --arg IMAGE "123456789012.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE' ecs-task-def-template.json > ecs-task-def.json
#       - aws ecs register-task-definition --cli-input-json file://ecs-task-def.json
#       - aws ecs update-service --cluster staging-cluster --service staging-service --force-new-deployment
#       - ./wait-for-staging-ready.sh http://staging.internal.example
#       - echo "Running OWASP ZAP baseline scan"
#       - docker run --rm owasp/zap2docker-stable zap-baseline.py -t http://staging.internal.example -r zap-baseline.html || true
#       - echo "Running OWASP ZAP full scan"
#       - docker run --rm owasp/zap2docker-stable zap-full-scan.py -t http://staging.internal.example -r zap-full.html || true
# artifacts:
#   files:
#     - sonar-output.txt
#     - zap-baseline.html
#     - zap-full.html
#   discard-paths: no


phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install phase ..."
  pre_build:
    commands:
      - echo "Pre build phase ..."
      - echo "Working dir: $(pwd)"
      #
      # Install lightweight tools (jq, unzip, wget/curl) using the available package manager
      #
      - |
        if command -v apt-get >/dev/null 2>&1; then
          echo "Using apt-get to install utilities"
          apt-get update -y
          apt-get install -y --no-install-recommends jq unzip wget curl
        elif command -v yum >/dev/null 2>&1; then
          echo "Using yum to install utilities"
          yum install -y jq unzip wget curl
        else
          echo "No apt-get or yum found; ensure jq/unzip/wget/curl are present in the image"
        fi
      #
      # Download & install SonarScanner CLI (robust to directory name/version)
      #
      - SCANNER_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.3.0.5189-linux-x64.zip"
      - echo "Downloading SonarScanner from $SCANNER_URL"
      - wget -q "$SCANNER_URL" -O sonar-scanner.zip || curl -sSL "$SCANNER_URL" -o sonar-scanner.zip
      - unzip -q sonar-scanner.zip || { echo "unzip failed"; exit 1; }
      - SCANNER_DIR=$(ls -d sonar-scanner-* 2>/dev/null | head -n1)
      - if [ -z "$SCANNER_DIR" ]; then echo "ERROR: sonar scanner directory not found after unzip" && ls -la && exit 1; fi
      - echo "SonarScanner dir: $SCANNER_DIR"
      - chmod +x "$SCANNER_DIR/bin/sonar-scanner"
      - export PATH="$PWD/$SCANNER_DIR/bin:$PATH"
      - echo "PATH after adding scanner: $PATH"
      - which sonar-scanner || echo "sonar-scanner not found in PATH"
      - sonar-scanner --version || echo "sonar-scanner --version failed"
  build:
    commands:
      - echo "Build phase ..."
      - echo "Running sonar-scanner analysis..."
      # run sonar-scanner; LOGIN should be your token (in CodeBuild secrets-manager mapping)
      - sonar-scanner -Dsonar.login="$LOGIN" -Dsonar.host.url="$HOST" -Dsonar.projectKey="$Project" -Dsonar.organization="$Organization"
      - echo "Waiting a few seconds for Sonar server to record analysis..."
      - sleep 5
      #
      # Check quality gate status via Sonar API and fail the build if it is ERROR
      # Use the SONAR host variable and token for auth (token as username and empty password)
      #
      - |
        echo "Querying Sonar quality gate status..."
        # Use basic auth with token as username and empty password
        curl -s -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" -o result.json || { echo "Failed to query Sonar API"; cat result.json || true; exit 1; }
        cat result.json
        STATUS=$(jq -r '.projectStatus.status' result.json)
        echo "Sonar quality gate status: $STATUS"
        if [ "$STATUS" = "ERROR" ]; then
          echo "Quality gate FAILED -> failing build"
          exit 1
        else
          echo "Quality gate OK or WARN ($STATUS) - continuing"
        fi
  post_build:
    commands:
      - echo "Post build phase ..."
      - echo "List current directory for artifacts:"
      - ls -la
      - echo "Done."
artifacts:
  files:
    - result.json
  discard-paths: no